### ISSUE TITLE
reorganizing guides

### ISSUE THREAD

**Issue by mehulkar** [emberjs/website#1092]
As I mentioned in #1064, I wanted to reorganize a little. Check out this hierarchy and let me know if I should continue down this line. 

The main reason for reorganizing is to make it make it easier to distinguish between ember and ember-data docs. The `models` folder is not enough for all data related guides and we definitely need good documentation for the power of adapters and serializers.

https://github.com/mehulkar/ember-website/tree/organize/source/guides
### TODO
- [ ] Rewrite how navigation is generated
- [ ] Revisit old adapter and store docs
- [ ] Simplify docs for ember-data
- [ ] More on per type adapters and serializers
- [ ] Better delineation between getting-started and behind-the-scenes docs
- [ ] Find another place for things that aren't guides (cookbooks, contributing, feature flags)
- [ ] create narrative between sections for ember-data so there is some continuity
- [ ] More docs on testing

@twokul
