### ISSUE TITLE
[META] Versioned API documentation

### ISSUE THREAD

**Issue by trek** [emberjs/website#1855]
Although the API docs live in-line with the code, I didn't want to post on emberjs/ember.js. There are some steps to get us to versions docs/guides:

## General
- [x] create shared Divshot team Ember team. 
- [x] add @trek and @rwjblue to this team.
- [x] create guides.emberjs.com repo on emberjs account

### API
- [x] create an [API browsing app](https://github.com/trek/ember-api/issues/5) 
- [x] ~~Create `api.emberjs.com` S3 Bucket~~^
- [x] ~~Make aforementioned bucket "web hosting enabled"~~^
- [x] ~~CNAME [`http://api.emberjs.com`](http://api.emberjs.com) to `api.emberjs.com.s3-website-us-east-1.amazonaws.com`~~
- [x] CNAME [`http://api.emberjs.com`](http://api.emberjs.com) to `ember-api.divshot.io`
- [x] create api.embejs.com repo on emberjs account
- [x] ~~create simple version file we can rev bump~~^
- [x] create index.html that immediately redirects to latest revision of the API docs
- [x] figure out how to generate older versions
- [x] figure out how to populate dropdown of previous versions
- [x] figure out where non-core but related (ember-data, ember-cli) projects live in the site
- [x] configure routing on divshot

### Guides
- [x] ~~Create `guides.emberjs.com` S3 Bucket~~
- [x] ~~Make aforementioned bucket "web hosting enabled"~~
- [x] ~~CNAME [`http://guides.emberjs.com`](http://guides.emberjs.com) to `guides.emberjs.com.s3-website-us-east-1.amazonaws.com`~~
- [x] create guides.emberjs.com repo on emberjs account
- [x] CNAME [`http://guides.emberjs.com`](http://guides.emberjs.com) to `ember-guides.divshot.io`
- [x] figure out how to generate older versions
- [x] figure out how to populate dropdown of previous versions
- [x] configure routing on divshot

## Workflow
Here's a general description of how the development and deployment process of versioned API and Guides works:

### API
There are two interrelated projects for versioned API browsing: the  The [API browser app] and the [API Divshot "app"](https://github.com/emberjs/api.emberjs.com). 

The [API browser app](http://api.emberjs.com) can read any YUIDoc library and convert the documentation into useful data structures _for a specific version of a library_. It will also produce a `seach.json` file which is the data structure needed for bulk insertion into elasticsearch. 

You can render the built application by running `ember build`. The resulting `dist` directory is copied into a new folder inside the API Divshot project that matches the version you are building, so if you built ember 1.4.0, this is moved to:

~/the-api-project/emberjs/1.4.0

Additionally, you need to add this into the `versions.json` file at the root of the repo. This file is loaded by all versions of the API browser to navigate between libraries and versions.

```json
{
  "libraries": ["ember.js", "ember-data", "rsvp"],
  "versions": {
    "ember.js": ["1.0.1", ..., "1.4.0"],
    "ember-data": ["1.0.1", ..., "1.4.0"]
  }
}
```

Not all libraries we'd like to document share the same version number, so we track these all separately. 

Every version of the API will have its own distinct app. We do not plan to backport future API browser features or styles to older publications.

Once you've moved the built application, you can deploy the API divshot app. This involves two steps currently:

* deploy to divshot with `divshot push`
* deploy search.json to swifttype with `???`

### Guides
There are two interrelated projects for versioned Guides browsing: the  The [Guides Source] and the [Guides Divshot "app"](https://github.com/emberjs/guides.emberjs.com). 

The Guides Source is a middleman application. The Guides Divshot app is where we snapshot a specific guides version for publication. Build the site by updating the version number in the config and running `middleman build`. Then copy the resulting directory into the Guides Divshot app.

Additionally, you need to add this into the `versions.json` file at the root of the repo. This file is loaded by all versions of the API browser to navigate between libraries and versions.

```json
  ["1.0.1", ... "1.4.0"],
```

This project tracks only the versions of Ember.js core. All guides materials related to a version of Ember.js are assumed to also be up-to-date with whatever dependency versions are required to run it.

Some questions we still need specific answers on for Guides.

- [x] how do you build a middleman app so that it considers  '/<some revision>` to be the root and not '/'? (likely a config option. Just need to google for what it is)
- [x] is there a good middleman plugin for generating a search.json similar to the json for the API browser so we can deploy version specific search? If not, we'll need to write one tailored to our very specific needs (https://github.com/emberjs/guides/issues/2)

Once you've moved the built application, you can deploy the divshot app. This involves two steps currently:

* deploy to divshot with `divshot push`
* deploy search  to swifttype with `???`

### Search
Search cuts across both API and Guides for several reasons:

* We only have one Swiftype account
* We only have two Swiftype engines on this account: one for production and one for testing

As a consequence, our setup is a little wonky. Right now, blog content, guides, and API are all the same document type ("a page") but splitting the content by version and by type means we need to get creative.

The future setup of Swiftype involves creating a new "document type" for every type of publication and its version

So, we'll have document types of `api-emberjs-140` (the search location for the API of ember 1.4.0), `api-rsvp-1.0` (the API search for RSVP 1.0),  `guides-140` (the guides for Ember.js 1.4.0), and  `site` (blog posts, main page, meetups, etc. Not versions).

It's still unclear which of these document type's we'd limit search to when searching at the top navigation. Possibly we just remove global search and have each app manage its own search.

Publishing search is also somewhat complicated by the fact that Swiftype "bulk" insert limits you to ~ 100 documents. They suggest https://gist.github.com/qhoxie/0a07a26149a8af04ee25 as a possible solution for getting around this (apparently you won't be rate limited?)

------
^ We've opted to not go with S3 and decided to try Divshot instead.

**Comment by MarkMurphy** [comment]
With regards to: **figure out how to populate dropdown of previous versions** why not use the Github API and a bit of javascript to make this happen?

**Comment by MarkMurphy** [comment]
I'd also like to note that a really nice to have feature (which will help keep things update-to-date and the docs bleeding edge) would be to include links to edit the documentation, within the documentation one is reading. Links to the related content on Github where people can make changes and submit pull-requests is how I've seen this implemented. Sails-JS and Elasticsearch do this and I think it's really smart.

**Comment by knownasilya** [comment]
@MarkMurphy we do this at the moment as well, although on a per-class basis: http://emberjs.com/api/classes/Ember.ActionHandler.html

![screen shot 2015-02-10 at 11 15 55 am](https://cloud.githubusercontent.com/assets/34726/6130874/378cef1c-b116-11e4-99e4-5e3ca290adaf.png)

Notice the pencil icon.

**Comment by MarkMurphy** [comment]
@knownasilya Thanks, I've been starring the the docs for a while now and have never noticed that! 

I'd like to suggest adding some **edit** text next to that and/or adding a footer under the content. That should make it more obvious and likely to bring in more contributors.

SailsJS has this as a content footer:


---
### Is something missing?
If you notice something we've missed or could be improved on, please follow [this link](http://sailsjs.org/#/documentation/concepts/Security) and submit a pull request to the sails-docs repo. Once we merge it, the changes will be immediately reflected on the website.

**Comment by bsclifton** [comment]
@trek: Under guides, did you have a typo in that checkbox? Did you mean (change highlighted):
"how do you build a middleman app so that it considers '/**guides**` to be the root and not '/'? (likely a config option. Just need to google for what it is)

I'm reading through everything above to get on the same page (would love to help!), that one just had me scratching my head

**Comment by trek** [comment]
@bsclifton if you check the current guides, that got figured out.

**Comment by bsclifton** [comment]
Great job on this :heart_eyes:

**Comment by joostdevries** [comment]
:+1:
