### ISSUE TITLE
[Meta issue] Update Ember Guides

### ISSUE THREAD

**Issue by mikepmunroe** [emberjs/website#1994]
The purpose of this issue is to organize all issues/meta issues for working towards the end goal of updating Ember Guides. This list is a living document and should be cultivated as we progress. 

This list is the beginning of a process to keep track of progress/what the blockers are/who is working on what.

To Do: Link each checkbox to a separate issue where appropriate and place Github handles next to tasks that have an owner

- [x] Find a way to version the guides, so all of the updates above don't totally pwn people still working on globals apps (#1855)
- [x] Make docs deploy a part of the standard Ember release train (#1855)
- [x] Update the guides to use Ember CLI.
- [ ] Improve docs structure (meta-issue: ember-cli/ember-cli#3307)
- [ ] Investigate status of @stefanpenner Ember-CLI POC and work towards building this out as a solid solution for integration with guides - @joostdevries leading effort to have a replacement for CLI 'js bin'
- [x] Don't bifurcate the community, with emberjs.com for noobs and ember-cli.com for "power users" (we need to climb the mountain together, as DHH says)
- [x] Remove any mention of features we've deprecated from the guides
- [x] Change examples from "globals-mode" to "module-mode"
- [x ] ~~Write a guide for how to translate module-mode examples to globals-mode~~
- [x] @bsclifton had the brilliant idea of a glossary in #1956 which we should flush out
- [x] Review all other things @bsclifton has started in #1956 
- [x] JSBin samples should be updated, and possibly just removed (since Ember CLI and JSBin don't play well at the moment)
- [X] ~~Investigate status of @fivetanley fivetanley/ember-cli-migrator as a proper tool to be documented within documentation for migration to Ember-CLI (@mikepmunroe)~~ Enough active development to warrant more testing and providing docs as an option.
- [x] Try to maintain a unified voice throughout the guides
- [x] ~~Schedule weekly standing meeting for stakeholders (@mikepmunroe)~~

**Comment by mikepmunroe** [comment]
link to issue for doc deploy as part of standard Ember release

**Comment by mikepmunroe** [comment]
cc: @ricardojmendez @stevekinney @bsclifton @joostdevries @tomdale @trek

**Comment by trek** [comment]
Probably a dup of #1855

**Comment by mikepmunroe** [comment]
Later today, I will merge this with #1855 and make sure #1855 has all items within this list or make adjustments accordingly.

Following that, I will close out this issue as a duplicate.

**Comment by stevekinney** [comment]
@mikepmunroe For the fourth checkbox, I think the goal is actually to _not_ bifurcate the community.

**Comment by mikepmunroe** [comment]
@stevekinney good catch. Working on merging this with #1855 and closing out as dupe now.

**Comment by mikepmunroe** [comment]
leaving this open as a separate issue and linked versioning and deployment tasks to #1855

**Comment by mikepmunroe** [comment]
@trek @rwjblue, We held our first standing meeting today and have a team of people ready to start tackling updates to Ember guides. Noticed that https://github.com/emberjs/guides.emberjs.com has been created. The repo is empty now. Can you confirm that would be the location for new updates? Is there something one of us can do to help get that repo populated? 

During the meeting we all confirmed that the guides should be updated with Ember CLI syntax and we will take on the burden of keeping docs up to date as changes are made to the best of our abilities.

**Comment by trek** [comment]
@mikepmunroe https://github.com/emberjs/guides.emberjs.com is where the built assets will go for divshot publication. It will be a repo that people should consider read-only. https://github.com/emberjs/guides will be where the source lives and is updated.

We need to first extract the guides and do a one publication with current globals semantics before moving over. The existing pages on http://emberjs.com/ will need to redirect to that the migrated version.

**Comment by trek** [comment]
I'm working on the initial extraction right now.

**Comment by mikepmunroe** [comment]
@trek Is the initial extraction still in progress?

**Comment by trek** [comment]
Yessir. https://github.com/emberjs/guides

**Comment by trek** [comment]
Although we can't publish yet until https://github.com/emberjs/guides/issues/2 is closed and we can search again.

**Comment by joostdevries** [comment]
@mikepmunroe to clarify: in ember-cli/ember-cli#3307 we're tracking an update to the Ember CLI site. My idea with that issue is that we'll be improving the structure of that site (split into several sections). I've isolated all the content dealing with consumers (app developers) and as this issue progresses we'll be taking that content out (moving it to the Ember guides).

**Comment by stefanpenner** [comment]
> Investigate status of @stefanpenner Ember-CLI POC and work towards building this out as a solid solution for integration with guides

what is this? Am i blocking something?

**Comment by mikepmunroe** [comment]
@stefanpenner, you are not blocking. 

This is in regards to the work you did on Ember-CLI jsbin proof of concept. We took an action item to follow up with you at some point to see what you had learned and who that might be able to transition to to take it home. There is an effort to update guides with CLI syntax, so being able to link to CLI based jsbins would be nice, if and when that is possible.

**Comment by stefanpenner** [comment]
ah ok.

cc @joostdevries ^^ may be related to some of our work

**Comment by vire** [comment]
@mikepmunroe based on some issues #2055 #1998 and [#10581](https://github.com/emberjs/ember.js/issues/10581)

I've started yesterday fixing jsbins - updating the header to following convention:
```
<script src="http://code.jquery.com/jquery.js"></script>
<script src="http://builds.emberjs.com/release/ember-template-compiler.js"></script>
<script src="http://builds.emberjs.com/release/ember.js"></script>
```

But today I've watched EmberConf 2015 - Opening Keynote :smile: and there were the new ember guides demo.

Question is now, should I continue in fixing jsbins for the website guide, or what will be the mechanism?

Complete removal of jsbins doesn't make sense to me since (except ember-cli) they are powerful at simple demonstration of concepts and provide easy hands on. (until there is a better way i wouldn't remove them...)

**Comment by trek** [comment]
We're stuck between a rock and a hard place. JSBin and its ilk are from a time before all the frameworks required project organization and build steps.

There's just not a great way (yet?) to express complex projects in a runnable way using these tools. I think we'll have to just remove for 2.0

**Comment by vire** [comment]
@trek sure, I've been thinking, how great it would be to have an online/virtual abstraction above ember-cli, demonstrating it's benefits.

 Q: Is there a good solution available allowing a user interact via browser (curd operations) with a ember-cli app instance? 

If not, is it worth to develop one - wouldn't it be easier to craft something like leanryou-ember-cli based on [learnyounode](https://github.com/rvagg/learnyounode) - an interactive shell tutorial that would share a same **learning track** as online ember guides? [suggestion]

As I understand the feature of versioned online guide it would be a walk-through ember API features wrapped with ember-cli concepts (folder struct, ES6 features - modules, naming conventions, assets). Still supporting a guide section with JSBin is helpful, especially to someone who is willing to do read/modify/evaluate learning.

What's the current road-map in terms of guides for the 2.0? is it somewhere stated?

**Comment by joostdevries** [comment]
@trek @vire @stefanpenner the jsbin issue is one that has been worrying me for quite a wile to be honest. I'm still not sure how we can actually get something of the ground. Right now, there are two issues: apps and addons. It would be great if you could create quick POC's of both, based on Ember CLI but entirely web-based.

I'm leaning towards building something but I want the solution to be as minimal as possible. Right now I'm thinking that a small layer on top of the Gist API would probably give the best user experience (so you can create a gist which would be merged into a bare Ember CLI app).

**Comment by joostdevries** [comment]
@trek @vire @stefanpenner POC:
- http://ember-playground.joostdvrs.com/f2c90713bdfdf54a262b
- https://gist.github.com/joostdevries/f2c90713bdfdf54a262b

**Comment by vire** [comment]
:+1: amazing!

**Comment by trek** [comment]
That's pretty great!

**Comment by joostdevries** [comment]
@trek http://ember-playground.joostdvrs.com/ It also supports CSS now. What would you need from me to use this in the guides?

**Comment by trek** [comment]
@joostdevries where the source for this?

**Comment by joostdevries** [comment]
@trek Was planning on putting it in a repo but was then pointed to @alexspeller s [Ember-Twiddle](https://github.com/alexspeller/ember-twiddle) ([demo](http://alexspeller.com/ember-twiddle/)) which is a lot more awesome and well-engineered. I'm working on a [PR](https://github.com/alexspeller/ember-twiddle/pull/1) adding Gists as a backend. I'll probably also be able to ask the interface heroes at my company to do some UI tweaks.

Maybe it would be an idea to host the final version on a emberjs.com subdomain?

**Comment by michaelrkn** [comment]
This should be closed.
