### ISSUE TITLE
Missing Deprecations in Deprecations Guide

### ISSUE THREAD

**Issue by Gaurav0** [emberjs/website#2256]
Please add to the deprecations guide here: http://emberjs.com/deprecations/v1.x/.

These are all of the deprecations in 1.13.x that need to be covered:
 
- http://emberjs.com/blog/2015/06/12/ember-1-13-0-released.html
  - [x] `Ember.CoreView` (63deb39ca7db138fe019765af79289131f18556f)
  - [x] `Ember.View` (#2195)
  - [x] `Ember.CollectionView` (#2265)
  - [x] `Ember.ContainerView` (#2265)
  - [x] `{{view 'some-helper'}}` (#2195)
  - [x] The `{{view}}` keyword for accessing properties on a view (#2198)
  - [x] The `{{controller}}` keyword for accessing properties on a controller (#2198)
  - [x] Options to the `{{#each` helper that trigger a legacy and poorly performing legacy layer. These options are: `itemView`, `itemViewClass`, `tagName`, `emptyView` and `emptyViewClass` (https://github.com/emberjs/website/pull/2328)
  - [x] The itemController argument for `{{#each`. (https://github.com/emberjs/website/pull/2328)
  - [x] `bind-attr` (#2305)
  - [x] Reading `this.get('template')` to check for a yielded block on components. (#2433)
  - [x] Non-block param `{{with` (e6cd07b8155c4e71c378d796f89df84ad4a9b14a)
  - [x] The view and viewClass params for `{{outlet}}` (#2433)
  - [x] `{{#each foo in bar}}{{/each}}` (e6cd07b8155c4e71c378d796f89df84ad4a9b14a)
  - [x] `Ember.EnumerableUtils` (#2433)
  - [x] Allow deprecated access to `template` in component to determine if a block was provided. (#2433)
  - [x] `Ember.LinkView` (#2197)
  - [x] `Ember.computed.any` (#2313)
  - [x] `Ember.Select` (#2201)
  - [x] `Ember.arrayComputed` (#2203)
  - [x] `Ember.ReduceComputedProperty` (#2433)
  - [x] `Ember.ArrayComputedProperty` (#2433)
  - [x] `Ember.reduceComputed` (#2203)
  - [x] `beforeOberver` (#2246)
  - [x] Modifying a property inside of `didInsertElement` (Reported in https://github.com/emberjs/ember.js/issues/12290) (#2433)
- https://github.com/emberjs/ember.js/blob/v1.13.1/CHANGELOG.md#1131-june-16-2015
  - [x] `Ember.immediateObserver`
  - [x] `Ember.ArrayController` (#2258)
  - [x] `Ember.RenderBuffer` (#2433)
- https://github.com/emberjs/ember.js/blob/v1.13.2/CHANGELOG.md#1132-june-16-2015
  - [x] `@guid`
  - [x] `@item`
- https://github.com/emberjs/ember.js/blob/v1.13.3/CHANGELOG.md#1133-july-5-2015
  - [x] `Ember.Object.createWithMixins` (#2295)
  - [x] `Ember.oneWay` (#2302)
  - [x] `Ember.keys` (#2296)
  - [x] `Ember.create` (#2296)
- https://github.com/emberjs/ember.js/blob/v1.13.5/CHANGELOG.md
  - [x] `Controller#needs` (#2266)
  - [x] `Ember.Freezable` (#2293)
  - [x] `frozenCopy` (#2428)
  - [x] `Ember.oneWay` (#2302)
  - [x] Deprecate reverse argument ordering in `Ember.observer`. (#2298)
  - [x] Deprecate slash for a namespace in the `{{render}}` helper. (#2428)
  - [x] `Function#observesBefore` (#2428)
  - [x] Add deprecation messages when using `Ember.get` / `Ember.set` in a certain ways. (#2428)
- https://github.com/emberjs/ember.js/blob/v1.13.6/CHANGELOG.md
  - [x] `Ember.Handlebars.makeViewHelper` (#2330)
  - [x] `Ember.HTMLBars.makeViewHelper` (#2330)
  - [x] `Ember.HTMLBars._registerHelper` (#2330)
  - [x] `Ember.HTMLBars.makeBoundHelper` (#2330)
  - [x] `Ember.Handlebars.makeBoundHelper` (#2330)
  - [x] `Ember.Handlebars.registerBoundHelper` (#2330)
  - [x] `Ember.Handlebars.helper` (#2330)
  - [x] `Ember.Handlebars.registerHelper` (#2330)
  - [x] `Ember.ContainerView` (#2265)
  - [x] `Ember.CollectionView` (#2265)
  - [x] Deprecate specifying `positionalParams` at extend time in favor of using static factory properties.
- https://github.com/emberjs/ember.js/blob/v1.13.7/CHANGELOG.md
  - [x] Deprecate using controller for `{{with}}` (72ab4e62854aae43af3262048315a95e497df29d)
  - [x] `{{#unbound}}{{/unbound}}` (#2289)
  - [x] `{{unbound}}` with multiple params (#2289)
  - [x] Deprecate specifying `render` function to `Ember.View` or `Ember.Component` at extend time. (72ab4e62854aae43af3262048315a95e497df29d)
  - [x] `Ember.TrackedArray` (72ab4e62854aae43af3262048315a95e497df29d)
  - [x] `Ember.SubArray` (72ab4e62854aae43af3262048315a95e497df29d)
  - [x] Deprecate using `@each` as a leaf node in a dependent key. (72ab4e62854aae43af3262048315a95e497df29d)

Thank you!

**Comment by wifelette** [comment]
I just went through all the minutes, added the weeks that were missing (as in, happened after this initial issue was filed) and pulled in all the specific details of the deprecations in each, as sublists. People have been fixing them piecemeal, so I wanted to be able to track exactly what was and wasn't done. 

Also, breaking it down like this hopefully makes these smaller tasks, so more people can jump in and help with little parts.

**Comment by trek** [comment]
I think @dstaley is working on a much larger version of this: https://github.com/dstaley/ember.js/issues/1

Although I don't understand why he's tracking the issue on his branch vs mainline

**Comment by trek** [comment]
Could the two of you work together to flesh out the full list please? Thanks.

**Comment by wifelette** [comment]
I commented there. Hopefully he'll jump in here and help :)

**Comment by dstaley** [comment]
@wifelette Definitely up for helping out! Just let me know what makes the most sense as far as where to put tracking issues, where to send PRs, etc. My original idea was to track the issues on my branches as PRs are sent to the branch, and then send on one big PR to mainline when it was done. If it makes more sense to track here and send PRs to a branch or something else just let me know.

**Comment by wifelette** [comment]
Howdy @dstaley! I think my thought was mostly the usual—PRs submitted to the website repo, added as a reference here, checked off when merged :)

I can't help _write_ much of this content, but I _can_ keep on top of it and get the PRs merged as quickly as possible, which has been part of the issue in the past. As in, sometimes people try helping with this, but then the PRs just sit around and waste away. Innocently of course, it's just that there's SO much else happening. So if I'm aggressively getting things merged, and we can get a _couple_ people to help, this should hopefully be a much quicker task than it previously was.

Having the main bit of work living here means it's more discoverable, so I'm hoping more people notice it, and I'll be able to draw more specific attention to it. (Also I hadn't noticed your thing when I spent the couple hours sifting through everything last night, or the job might've been a _lot_ easier :stuck_out_tongue_winking_eye: Sounds like my life :smile: )

It's probably helpful to comment here when self-assigning an item, or add a username after the list item, a.k.a. "I'm tackling X", so other folks choose different things to tackle.

**Comment by wifelette** [comment]
Update: a bunch of helpful folk are hanging in the #documentation channel on the [Ember Community Slack](https://ember-community-slackin.herokuapp.com/), interested in this very topic :)

**Comment by wifelette** [comment]
So we made a _bunch_ of progress on this these last few day. Thanks so much to everyone who stepped up!

I've heard a couple of people say that they don't feel confident enough to jump in and try and help, or that while they understood 80% of the reason for a particular deprecation, they weren't jumping in because of the bits they _didn't_ understand. 

To be clear, it's _totally_ great to open a PR that isn't 100% ready to merge. If you can do _some_ of the work, other people can jump in and help, and together we'll get more of this tackled. Also, pointing out exactly what part you're having trouble understanding makes it much easier for a core team member or anyone really, to quickly comment to explain the part you need help. So definitely don't think you can't help out if you're not all the way there yet <3 We'll take all the help we can get!

**Comment by martndemus** [comment]
`{{#each foo in bar}}{{/each}}` is already documented here: http://emberjs.com/deprecations/v1.x/#toc_code-in-code-syntax-for-code-each-code

**Comment by wifelette** [comment]
Thanks @martndemus, updated and linked to commit :)

**Comment by workmanw** [comment]
`Ember.SortableMixin` seems to be gone in 2.0. I briefly looked around, but found no mention of it's deprecation or disappearance.

**Comment by ultimatemonty** [comment]
Request to add https://github.com/emberjs/ember.js/issues/11493 to the deprecations guide along with the reasoning behind it and acceptable alternatives. There are only 2 events that run on component first run (`didInitAttrs` and `didInsertElement`) and the only place to init something like a jquery plugin wrapper is `didInsertElement`.

Thanks for all you folks do!

**Comment by wifelette** [comment]
@ultimatemonty Added to the list, thanks!

**Comment by wifelette** [comment]
@workmanw `SortableMixin` was part of the controller feature in 1.13, and it was removed (along with many other controller deprecations). However, it's still available in the [Legacy Controller Addon](https://github.com/emberjs/ember-legacy-controllers) (at https://github.com/emberjs/ember-legacy-controllers/blob/master/addon/utils/sortable-mixin.js), and it would great to get a PR pointing people to the Mixin for that feature :)

**Comment by workmanw** [comment]
@wifelette et al -- I'd be happy to submit a pull for `SortableMixin` ... but it wasn't actually deprecated in a literal sense, it was just kind of removed without warning. So it doesn't fit within the literal sense of "DEPRECATIONS ADDED IN 1.13". But if that seems okay, I'll open a PR.

**Comment by workmanw** [comment]
@wifelette Now that Ember.SortableMixin has been deprecated in Ember 1.x. I've added #2405.

**Comment by toddjordan** [comment]
I can start gradually working through the some of the rest of these.  I'll start at the batch from 1.13.7 and start working my way back.  Starting with TrackedArray and SubArray...

**Comment by toddjordan** [comment]
ok, this week I'll move on to the `@guid` and `@item` deprecations from 1.13.2

**Comment by toddjordan** [comment]
Moving on to the remaining 1.13.5 deprecations

**Comment by acorncom** [comment]
@wifelette @toddjordan #2428 was just merged.  I just updated the checkboxes above to reflect that, which means at this point, I believe all deprecations are documented.  Is that true?

@wifelette I'll leave the pleasure of closing this issue to you :-)

**Comment by wifelette** [comment]
Hah! I'm out this week and was legit sad that someone else would get to close it ;) Thanks everyone for helping make this happen!

**Comment by Gaurav0** [comment]
Thank you all for your hard work on this.
